### ISSUE TITLE
ver1.0 todo list

### ISSUE THREAD

**Issue by 129lovely** [do-olaf/cash-book-app#3]
> Read

- [ ] search 버튼 로직 수정 (search 버튼 없애고, 그냥 날짜 설정만 하면 바로 새롭게 리스트 로드)

- [x] layout 수정

- [x] search 버튼 활성화

- [x] 날짜 -> idx 순서로 오름차순 정렬

- [x] search 버튼 눌렀을 때 시작날짜 > 끝날짜 일경우 검색 불가능 toast 띄울 것

- [x] 메모, id 화면에서 삭제

- [x] 금액 1000단위로 ',' 넣기

- [x] 날짜 DB 오류(?) 확인

- [x] 수입/지출 0/1 아닌 "수입"/"지출"로 나타내기

**Comment by YunSerin** [comment]
> Create

- [x]  insert구현

> Delete

- [x] delete위한 checkbox맨 왼쪽

- [x] 전체 삭제 버튼

> Update

- [x] 오늘쪽에 .. 버튼 추가

- [x] update layout 띄우기 및 activity 작성

- [x] data받아와서 create 레이아웃과 같이 창 띄우기 (금액, 메모만 성공)

- [x] update 누르면 수정 ( cancel 누르면 닫기)

> ETC

- [ ] DB crud 관련 메서드 따로 모아서 클래스 생성

- [ ] 전체적인 ui 수정 (좀더 보기좋게!)

- [ ] 코드 줄이기 (리팩토링)
